version: '2'
services:
  api:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/app:delegated
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:7-fpm
    volumes:
      - ./:/app:delegated
  db:
    image: mysql:5.7
    env_file: .env
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql