version: '2'
services:
  app:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/app:delegated
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:7-fpm
    volumes:
      - ./:/app:delegated
  db:
    image: mariadb:10.1.21
    env_file: .env
    volumes:
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/data/:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"