version: '2'
services:
  app:
    container_name: app
    image: nginx:1.14.2
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - ./:/app:delegated
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - database
    depends_on:
      - php
  php:
    container_name: php
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    env_file: .env
    volumes:
      - ./:/app:delegated
  database:
    container_name: database
    image: mariadb:10.3
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    env_file: .env
    ports:
      - 8000:80