version: '2'
services:
  app:
    container_name: app
    image: nginx:1.14.2
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - database
    depends_on:
      - php
  php:
    container_name: php
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    env_file: .env
    volumes:
      - ./:/var/www/html
  database:
    container_name: database
    image: mariadb:10.3
    ports:
      - 3306:3306
    volumes:
      - ./docker/database/data:/var/lib/mysql
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    env_file: .env
    ports:
      - 8000:80
    depends_on:
      - database