version: '2'
services:
  app:
    image: nginx:1.14.2
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - ./:/app:delegated
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - database
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    env_file: .env
    volumes:
      - ./:/app:delegated
  database:
    image: mariadb:10.3
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    ports:
      - 8000:80