version: '2'
services:
  app:
    image: nginx:1.14.2
    ports:
      - "8080:80"
    volumes:
      - ./:/app:delegated
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:7.3.3-fpm
    volumes:
      - ./:/app:delegated
  db:
    image: mariadb:10.3
    env_file: .env
    volumes:
      - ./database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"